"""Create tables

Revision ID: 957ce248679a
Revises: 
Create Date: 2022-10-28 12:13:54.846541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957ce248679a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('parent_id', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foundations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=24), nullable=False),
    sa.Column('address', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('name')
    )
    op.create_table('raw_materials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_areas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=24), nullable=False),
    sa.Column('foundation_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['foundation_id'], ['foundations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=24), nullable=False),
    sa.Column('address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('foundation_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['foundation_id'], ['foundations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=32), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.SmallInteger(), nullable=False),
    sa.Column('category_id', sa.SmallInteger(), nullable=False),
    sa.Column('storage_id', sa.SmallInteger(), nullable=True),
    sa.Column('production_area_id', sa.SmallInteger(), nullable=True),
    sa.Column('is_shipment', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['raw_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['production_area_id'], ['production_areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_id'], ['storages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('storages')
    op.drop_table('production_areas')
    op.drop_table('roles')
    op.drop_table('raw_materials')
    op.drop_table('foundations')
    op.drop_table('categories')
    # ### end Alembic commands ###
